import type { Metadata } from "next";
import { Audiowide, Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({
	subsets: ["latin"],
	variable: "--font-inter",
	display: "swap",
});
const audiowide = Audiowide({
	weight: "400",
	subsets: ["latin"],
	variable: "--font-audiowide",
	display: "swap",
});
export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<body className={`${inter.variable} ${audiowide.variable}`}>
				{/**        <Navbar />*/}
				{children}{" "}
			</body>
		</html>
	);
}
